package com.abandon.domain;

import java.util.Date;

public class EnquipmentInfo {
    
	private String meetingroomName;
	

	private String userName;
	
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquipment_info.enquipment_id
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    private Integer enquipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquipment_info.user_id
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquipment_info.meetingroom_id
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    private Integer meetingroomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquipment_info.enquipment_name
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    private String enquipmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquipment_info.procurement_time
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    private Date procurementTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquipment_info.enquipment_price
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    private Double enquipmentPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquipment_info.enquipment_remerk
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    private String enquipmentRemerk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquipment_info.enquipment_id
     *
     * @return the value of enquipment_info.enquipment_id
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    public Integer getEnquipmentId() {
        return enquipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquipment_info.enquipment_id
     *
     * @param enquipmentId the value for enquipment_info.enquipment_id
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    public void setEnquipmentId(Integer enquipmentId) {
        this.enquipmentId = enquipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquipment_info.user_id
     *
     * @return the value of enquipment_info.user_id
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquipment_info.user_id
     *
     * @param userId the value for enquipment_info.user_id
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquipment_info.meetingroom_id
     *
     * @return the value of enquipment_info.meetingroom_id
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    public Integer getMeetingroomId() {
        return meetingroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquipment_info.meetingroom_id
     *
     * @param meetingroomId the value for enquipment_info.meetingroom_id
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    public void setMeetingroomId(Integer meetingroomId) {
        this.meetingroomId = meetingroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquipment_info.enquipment_name
     *
     * @return the value of enquipment_info.enquipment_name
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    public String getEnquipmentName() {
        return enquipmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquipment_info.enquipment_name
     *
     * @param enquipmentName the value for enquipment_info.enquipment_name
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    public void setEnquipmentName(String enquipmentName) {
        this.enquipmentName = enquipmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquipment_info.procurement_time
     *
     * @return the value of enquipment_info.procurement_time
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    public Date getProcurementTime() {
        return procurementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquipment_info.procurement_time
     *
     * @param procurementTime the value for enquipment_info.procurement_time
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    public void setProcurementTime(Date procurementTime) {
        this.procurementTime = procurementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquipment_info.enquipment_price
     *
     * @return the value of enquipment_info.enquipment_price
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    public Double getEnquipmentPrice() {
        return enquipmentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquipment_info.enquipment_price
     *
     * @param enquipmentPrice the value for enquipment_info.enquipment_price
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    public void setEnquipmentPrice(Double enquipmentPrice) {
        this.enquipmentPrice = enquipmentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquipment_info.enquipment_remerk
     *
     * @return the value of enquipment_info.enquipment_remerk
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    public String getEnquipmentRemerk() {
        return enquipmentRemerk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquipment_info.enquipment_remerk
     *
     * @param enquipmentRemerk the value for enquipment_info.enquipment_remerk
     *
     * @mbg.generated Mon Dec 17 23:21:18 CST 2018
     */
    public void setEnquipmentRemerk(String enquipmentRemerk) {
        this.enquipmentRemerk = enquipmentRemerk;
    }
	   
	public String getMeetingroomName() {
		return meetingroomName;
	}

	public void setMeetingroomName(String meetingroomName) {
		this.meetingroomName = meetingroomName;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Override
	public String toString() {
		return "EnquipmentInfo [meetingroomName=" + meetingroomName + ", userName=" + userName + ", enquipmentId="
				+ enquipmentId + ", userId=" + userId + ", meetingroomId=" + meetingroomId + ", enquipmentName="
				+ enquipmentName + ", procurementTime=" + procurementTime + ", enquipmentPrice=" + enquipmentPrice
				+ ", enquipmentRemerk=" + enquipmentRemerk + "]";
	}

	
}
