package com.abandon.domain;

import java.sql.Date;

public class MeetingroomSetting {
	private String mark;
	private String userName;
	
	private String meetingroomName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_setting.bespeak_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private Integer bespeakId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_setting.meetingroom_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private Integer meetingroomId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_setting.user_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_setting.apply_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private Date applyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_setting.meeting_name
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String meetingName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_setting.strat_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private Date stratTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_setting.end_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_setting.meetingroom_note
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String meetingroomNote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_setting.bespeak_state
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String bespeakState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_setting.auditing_man
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String auditingMan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_setting.auditing_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private Date auditingTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_setting.auditing_info
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String auditingInfo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_setting.bespeak_id
	 * @return  the value of meetingroom_setting.bespeak_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public Integer getBespeakId() {
		return bespeakId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_setting.bespeak_id
	 * @param bespeakId  the value for meetingroom_setting.bespeak_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setBespeakId(Integer bespeakId) {
		this.bespeakId = bespeakId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_setting.meetingroom_id
	 * @return  the value of meetingroom_setting.meetingroom_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public Integer getMeetingroomId() {
		return meetingroomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_setting.meetingroom_id
	 * @param meetingroomId  the value for meetingroom_setting.meetingroom_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setMeetingroomId(Integer meetingroomId) {
		this.meetingroomId = meetingroomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_setting.user_id
	 * @return  the value of meetingroom_setting.user_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_setting.user_id
	 * @param userId  the value for meetingroom_setting.user_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_setting.apply_time
	 * @return  the value of meetingroom_setting.apply_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public Date getApplyTime() {
		return applyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_setting.apply_time
	 * @param date  the value for meetingroom_setting.apply_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setApplyTime(Date date) {
		this.applyTime = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_setting.meeting_name
	 * @return  the value of meetingroom_setting.meeting_name
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getMeetingName() {
		return meetingName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_setting.meeting_name
	 * @param meetingName  the value for meetingroom_setting.meeting_name
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setMeetingName(String meetingName) {
		this.meetingName = meetingName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_setting.strat_time
	 * @return  the value of meetingroom_setting.strat_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public Date getStratTime() {
		return stratTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_setting.strat_time
	 * @param stratTime  the value for meetingroom_setting.strat_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setStratTime(Date stratTime) {
		this.stratTime = stratTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_setting.end_time
	 * @return  the value of meetingroom_setting.end_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_setting.end_time
	 * @param endTime  the value for meetingroom_setting.end_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_setting.meetingroom_note
	 * @return  the value of meetingroom_setting.meetingroom_note
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getMeetingroomNote() {
		return meetingroomNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_setting.meetingroom_note
	 * @param meetingroomNote  the value for meetingroom_setting.meetingroom_note
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setMeetingroomNote(String meetingroomNote) {
		this.meetingroomNote = meetingroomNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_setting.bespeak_state
	 * @return  the value of meetingroom_setting.bespeak_state
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getBespeakState() {
		return bespeakState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_setting.bespeak_state
	 * @param bespeakState  the value for meetingroom_setting.bespeak_state
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setBespeakState(String bespeakState) {
		this.bespeakState = bespeakState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_setting.auditing_man
	 * @return  the value of meetingroom_setting.auditing_man
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getAuditingMan() {
		return auditingMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_setting.auditing_man
	 * @param auditingMan  the value for meetingroom_setting.auditing_man
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setAuditingMan(String auditingMan) {
		this.auditingMan = auditingMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_setting.auditing_time
	 * @return  the value of meetingroom_setting.auditing_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public Date getAuditingTime() {
		return auditingTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_setting.auditing_time
	 * @param auditingTime  the value for meetingroom_setting.auditing_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setAuditingTime(Date auditingTime) {
		this.auditingTime = auditingTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_setting.auditing_info
	 * @return  the value of meetingroom_setting.auditing_info
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getAuditingInfo() {
		return auditingInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_setting.auditing_info
	 * @param auditingInfo  the value for meetingroom_setting.auditing_info
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setAuditingInfo(String auditingInfo) {
		this.auditingInfo = auditingInfo;
	}
	
	
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getMeetingroomName() {
		return meetingroomName;
	}

	public void setMeetingroomName(String meetingroomName) {
		this.meetingroomName = meetingroomName;
	}
	
	public String getMark() {
		return mark;
	}

	public void setMark(String mark) {
		this.mark = mark;
	}

	@Override
	public String toString() {
		return "MeetingroomSetting [userName=" + userName + ", meetingroomName=" + meetingroomName + ", bespeakId="
				+ bespeakId + ", meetingroomId=" + meetingroomId + ", userId=" + userId + ", applyTime=" + applyTime
				+ ", meetingName=" + meetingName + ", stratTime=" + stratTime + ", endTime=" + endTime
				+ ", meetingroomNote=" + meetingroomNote + ", bespeakState=" + bespeakState + ", auditingMan="
				+ auditingMan + ", auditingTime=" + auditingTime + ", auditingInfo=" + auditingInfo + "]";
	}

	
	
}