package com.abandon.domain;

public class MeetingroomInfo {
	
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_info.meetingroom_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private Integer meetingroomId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_info.meetingroom_name
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String meetingroomName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_info.meetingroom_size
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String meetingroomSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_info.meetingroom_note
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String meetingroomNote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column meetingroom_info.mmeetingroom_state
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String mmeetingroomState;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_info.meetingroom_id
	 * @return  the value of meetingroom_info.meetingroom_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public Integer getMeetingroomId() {
		return meetingroomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_info.meetingroom_id
	 * @param meetingroomId  the value for meetingroom_info.meetingroom_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setMeetingroomId(Integer meetingroomId) {
		this.meetingroomId = meetingroomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_info.meetingroom_name
	 * @return  the value of meetingroom_info.meetingroom_name
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getMeetingroomName() {
		return meetingroomName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_info.meetingroom_name
	 * @param meetingroomName  the value for meetingroom_info.meetingroom_name
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setMeetingroomName(String meetingroomName) {
		this.meetingroomName = meetingroomName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_info.meetingroom_size
	 * @return  the value of meetingroom_info.meetingroom_size
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getMeetingroomSize() {
		return meetingroomSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_info.meetingroom_size
	 * @param meetingroomSize  the value for meetingroom_info.meetingroom_size
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setMeetingroomSize(String meetingroomSize) {
		this.meetingroomSize = meetingroomSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_info.meetingroom_note
	 * @return  the value of meetingroom_info.meetingroom_note
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getMeetingroomNote() {
		return meetingroomNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_info.meetingroom_note
	 * @param meetingroomNote  the value for meetingroom_info.meetingroom_note
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setMeetingroomNote(String meetingroomNote) {
		this.meetingroomNote = meetingroomNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column meetingroom_info.mmeetingroom_state
	 * @return  the value of meetingroom_info.mmeetingroom_state
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getMmeetingroomState() {
		return mmeetingroomState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column meetingroom_info.mmeetingroom_state
	 * @param mmeetingroomState  the value for meetingroom_info.mmeetingroom_state
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setMmeetingroomState(String mmeetingroomState) {
		this.mmeetingroomState = mmeetingroomState;
	}

	@Override
	public String toString() {
		return "MeetingroomInfo [meetingroomId=" + meetingroomId + ", meetingroomName=" + meetingroomName
				+ ", meetingroomSize=" + meetingroomSize + ", meetingroomNote=" + meetingroomNote
				+ ", mmeetingroomState=" + mmeetingroomState + "]";
	}
	
	
}