package com.abandon.domain;

import java.util.Date;

public class UserInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_pw
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String userPw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_name
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_url
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String userUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_sex
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String userSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_age
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private Integer userAge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_phone
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String userPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_beizhu
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String userBeizhu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private Date userTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.is_user
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String isUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.user_anthority
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	private String userAnthority;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_id
	 * @return  the value of user_info.user_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_id
	 * @param userId  the value for user_info.user_id
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_pw
	 * @return  the value of user_info.user_pw
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getUserPw() {
		return userPw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_pw
	 * @param userPw  the value for user_info.user_pw
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setUserPw(String userPw) {
		this.userPw = userPw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_name
	 * @return  the value of user_info.user_name
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_name
	 * @param userName  the value for user_info.user_name
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_url
	 * @return  the value of user_info.user_url
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getUserUrl() {
		return userUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_url
	 * @param userUrl  the value for user_info.user_url
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setUserUrl(String userUrl) {
		this.userUrl = userUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_sex
	 * @return  the value of user_info.user_sex
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getUserSex() {
		return userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_sex
	 * @param userSex  the value for user_info.user_sex
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_age
	 * @return  the value of user_info.user_age
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public Integer getUserAge() {
		return userAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_age
	 * @param userAge  the value for user_info.user_age
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setUserAge(Integer userAge) {
		this.userAge = userAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_phone
	 * @return  the value of user_info.user_phone
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_phone
	 * @param userPhone  the value for user_info.user_phone
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_beizhu
	 * @return  the value of user_info.user_beizhu
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getUserBeizhu() {
		return userBeizhu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_beizhu
	 * @param userBeizhu  the value for user_info.user_beizhu
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setUserBeizhu(String userBeizhu) {
		this.userBeizhu = userBeizhu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_time
	 * @return  the value of user_info.user_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public Date getUserTime() {
		return userTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_time
	 * @param userTime  the value for user_info.user_time
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setUserTime(Date userTime) {
		this.userTime = userTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.is_user
	 * @return  the value of user_info.is_user
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getIsUser() {
		return isUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.is_user
	 * @param isUser  the value for user_info.is_user
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setIsUser(String isUser) {
		this.isUser = isUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.user_anthority
	 * @return  the value of user_info.user_anthority
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public String getUserAnthority() {
		return userAnthority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.user_anthority
	 * @param userAnthority  the value for user_info.user_anthority
	 * @mbg.generated  Mon Dec 17 23:21:18 CST 2018
	 */
	public void setUserAnthority(String userAnthority) {
		this.userAnthority = userAnthority;
	}

	@Override
	public String toString() {
		return "UserInfo [userId=" + userId + ", userPw=" + userPw + ", userName=" + userName + ", userUrl=" + userUrl
				+ ", userSex=" + userSex + ", userAge=" + userAge + ", userPhone=" + userPhone + ", userBeizhu="
				+ userBeizhu + ", userTime=" + userTime + ", isUser=" + isUser + ", userAnthority=" + userAnthority
				+ "]";
	}
	
}